version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    security_opt:
      - no-new-privileges:true
    # Add resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    # Additional security measures
    cap_drop:
      - ALL
    # Read-only root filesystem
    read_only: true
    # Add temporary storage for runtime requirements
    tmpfs:
      - /tmp:size=50M
      - /app/.next/cache:size=100M
    # Add healthcheck
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s